name: Feature request
description: Suggest an idea or enhancement for disauth
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Help us understand how this change makes disauth better for everyone.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature or change you would like to see.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve? Is there a related issue?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like to see this implemented? Include API shape or pseudo-code if helpful.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you looked at other approaches or workarounds?
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or references.
